prod_dbinfo: &prod_dbinfo
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: myusername
    password:

development:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: myusername
    password:
    database: skepseis_development
    
test:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: myusername
    password:
    database: skepseis_test

staging:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: myusername
    password:
    database: skepseis_staging

production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: myusername
    password:
    database: skepseis_production


