dbinfo: &dbinfo
    adapter: mysql
    encoding: utf8
    host: localhost
    username: root
    password:

development:
    database: skepseis_development
    <<: *dbinfo

test:
    database: skepseis_test
    <<: *dbinfo

# Production and Staging will be on Heroku

prod_dbinfo: &prod_dbinfo
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: postgres
    password:

staging:
    database: skepseis_staging
    <<: *prod_dbinfo

production:
    database: skepseis_production
    <<: *prod_dbinfo

